Repository Team-Smeme/Smeem-iOS, pull requests merged in 2023-05, with the labels that each got.

#11 [Feat] #9 - 캘린더 추가
  Smeem-iOS/Smeem-iOS.xcodeproj/project.pbxproj
  Smeem-iOS/Smeem-iOS/Global/Extensions/UIScreen+.swift
  Smeem-iOS/Smeem-iOS/Global/Extensions/UIView+.swift
  Smeem-iOS/Smeem-iOS/Global/Extensions/UIViewController+.swift
  Smeem-iOS/Smeem-iOS/Presentation/Home/HomeViewController.swift
Labels: 쭈 🦋, Feat

#13 [Feat] #12 - Splash, Bottom Sheet 구현
  Smeem-iOS/Smeem-iOS.xcodeproj/project.pbxproj
  Smeem-iOS/Smeem-iOS/Presentation/BottomSheet/BottomSheetView.swift
  Smeem-iOS/Smeem-iOS/Presentation/BottomSheet/BottomSheetViewController.swift
  Smeem-iOS/Smeem-iOS/Presentation/Splash/SplashViewController.swift
  Smeem-iOS/Smeem-iOS/Supports/SceneDelegate.swift
Labels: 짠 ✨, Feat

#17 [Fix] 충돌 해결
  Smeem-iOS/Smeem-iOS.xcodeproj/project.pbxproj
Labels: 짠 ✨

#15 [FEAT] #8 - Design System
  Smeem-iOS/Smeem-iOS.xcodeproj/project.pbxproj
  Smeem-iOS/Smeem-iOS.xcodeproj/project.xcworkspace/xcuserdata/joonbaek.xcuserdatad/UserInterfaceState.xcuserstate
  Smeem-iOS/Smeem-iOS/Global/Literals/ColorLiterals.swift
  Smeem-iOS/Smeem-iOS/Global/UIComponents/CustomToastView.swift
  Smeem-iOS/Smeem-iOS/Global/UIComponents/RandomSubjectView.swift
Labels: 쭌 🍆

#20 [Feat] #16 - alarm collectionView 구현
  Smeem-iOS/Smeem-iOS.xcodeproj/project.pbxproj
  Smeem-iOS/Smeem-iOS/Presentation/Alarm/AlarmCollectionView.swift
  Smeem-iOS/Smeem-iOS/Presentation/Alarm/AlarmCollectionViewCell.swift
  Smeem-iOS/Smeem-iOS/Presentation/Alarm/DatePickerFooterView.swift
Labels: 짠 ✨, Feat

#22 [Fix] #21 - Local에 없는 파일 삭제
  Smeem-iOS/Smeem-iOS.xcodeproj/project.pbxproj
Labels: 짠 ✨, Fix

#25 [Feat] #24 - 닉네임 설정 및 서비스 이용약관 UI 구현
  Smeem-iOS/Smeem-iOS.xcodeproj/project.pbxproj
  Smeem-iOS/Smeem-iOS/Global/Extensions/UITextField+.swift
  Smeem-iOS/Smeem-iOS/Presentation/Onboarding/Goal/GoalCollectionViewCell.swift
  Smeem-iOS/Smeem-iOS/Presentation/Onboarding/Nickname/UserNickNameViewController.swift
  Smeem-iOS/Smeem-iOS/Presentation/Onboarding/Service/ServiceAcceptCollectionViewCell.swift
  Smeem-iOS/Smeem-iOS/Presentation/Onboarding/Service/ServiceAcceptViewController.swift
Labels: 짠 ✨, Feat

#30 [Feat] #10 - 셀 디자인 커스텀
  Smeem-iOS/Smeem-iOS.xcodeproj/project.pbxproj
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/monthToday.imageset/Contents.json
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/monthToday.imageset/monthToday.png
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/monthToday.imageset/monthToday@2x.png
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/monthToday.imageset/monthToday@3x.png
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/monthday.imageset/Contents.json
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/monthday.imageset/monthday.png
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/monthday.imageset/monthday@2x.png
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/monthday.imageset/monthday@3x.png
  Smeem-iOS/Smeem-iOS/Presentation/Home/CalendarCell.swift
  Smeem-iOS/Smeem-iOS/Presentation/Home/HomeViewController.swift
Labels: 쭈 🦋, Feat

#35 [Feat] #31 - 캘린더 하단 다이어리 썸네일뷰 구현
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/noDiary.imageset/Contents.json
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/noDiary.imageset/noDiary.png
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/noDiary.imageset/noDiary@2x.png
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/noDiary.imageset/noDiary@3x.png
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/rightArrow.imageset/Contents.json
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/rightArrow.imageset/rightArrow.png
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/rightArrow.imageset/rightArrow@2x.png
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/rightArrow.imageset/rightArrow@3x.png
  Smeem-iOS/Smeem-iOS/Presentation/Home/CalendarCell.swift
  Smeem-iOS/Smeem-iOS/Presentation/Home/HomeViewController.swift
Labels: 쭈 🦋, Feat

#44 [Fix] #43 - 라이브러리 재설치
  Smeem-iOS/Smeem-iOS.xcodeproj/project.pbxproj
  Smeem-iOS/Smeem-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: 짠 ✨, Fix
