Repository Team-Smeme/Smeem-iOS, pull requests merged in 2023-06, with the labels that each got.

#45 [Feat] #37 - 외국어로 일기 쓰기 뷰 기본 기능 구현
  Smeem-iOS/Smeem-iOS.xcodeproj/project.pbxproj
  Smeem-iOS/Smeem-iOS.xcodeproj/project.xcworkspace/xcuserdata/joonbaek.xcuserdatad/UserInterfaceState.xcuserstate
  Smeem-iOS/Smeem-iOS/Presentation/ForeignDiary/ForeignDiaryViewController.swift
Labels: 쭌 🍆, Feat

#46 [Feat] #32 - 마이페이지 닉네임 변경 뷰 구현
  Smeem-iOS/Smeem-iOS.xcodeproj/project.pbxproj
  Smeem-iOS/Smeem-iOS/Presentation/MyPage/EditNicknameViewController.swift
Labels: 쫑 🎀, Feat

#39 [Feat] #29 - 푸시 알림 권한, 활동 추적 권한 팝업
  Smeem-iOS/Smeem-iOS/Info.plist
  Smeem-iOS/Smeem-iOS/Presentation/Onboarding/Alarm/AlarmSettingViewController.swift
  Smeem-iOS/Smeem-iOS/Supports/AppDelegate.swift
Labels: 짠 ✨, Feat

#48 [Setting] #47 - 아이콘, 앱 아이콘 추가
  Smeem-iOS/Smeem-iOS.xcodeproj/project.pbxproj
  Smeem-iOS/Smeem-iOS/Global/Literals/ConstantImage.swift
  Smeem-iOS/Smeem-iOS/Global/Literals/ImageLiterals.swift
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/AppIcon/AppIcon.appiconset/1024.png
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/AppIcon/AppIcon.appiconset/114.png
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/AppIcon/AppIcon.appiconset/120.png
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/AppIcon/AppIcon.appiconset/180.png
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/AppIcon/AppIcon.appiconset/29.png
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/AppIcon/AppIcon.appiconset/40.png
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/AppIcon/AppIcon.appiconset/57.png
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/AppIcon/AppIcon.appiconset/58.png
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/AppIcon/AppIcon.appiconset/60.png
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/AppIcon/AppIcon.appiconset/80.png
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/AppIcon/AppIcon.appiconset/87.png
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/AppIcon/AppIcon.appiconset/Contents.json
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/AppIcon/Contents.json
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/icnBack.imageset/Contents.json
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/icnBack.imageset/icnBack.png
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/icnBack.imageset/icnBack@2x.png
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/icnBack.imageset/icnBack@3x.png
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/icnCancelGrey.imageset/Contents.json
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/icnCancelGrey.imageset/icnCancelGrey.png
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/icnCancelGrey.imageset/icnCancelGrey@2x.png
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/icnCancelGrey.imageset/icnCancelGrey@3x.png
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/icnCancelSmall.imageset/Contents.json
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/icnCancelSmall.imageset/icnCancelSmall.png
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/icnCancelSmall.imageset/icnCancelSmall@2x.png
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/icnCancelSmall.imageset/icnCancelSmall@3x.png
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/icnCancelWhite.imageset/Contents.json
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/icnCancelWhite.imageset/icnCancelWhite.png
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/icnCancelWhite.imageset/icnCancelWhite@2x.png
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/icnCancelWhite.imageset/icnCancelWhite@3x.png
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/icnCheck.imageset/Contents.json
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/icnCheck.imageset/icnCheck.png
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/icnCheck.imageset/icnCheck@2x.png
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/icnCheck.imageset/icnCheck@3x.png
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/icnCheckInactive.imageset/Contents.json
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/icnCheckInactive.imageset/icnCheckInactive.png
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/icnCheckInactive.imageset/icnCheckInactive@2x.png
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/icnCheckInactive.imageset/icnCheckInactive@3x.png
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/icnMore.imageset/Contents.json
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/icnMore.imageset/icn_more.png
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/icnMore.imageset/icn_more@2x.png
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/icnMore.imageset/icn_more@3x.png
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/icnMoreHoriz.imageset/Contents.json
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/icnMoreHoriz.imageset/icnMoreHoriz.png
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/icnMoreHoriz.imageset/icnMoreHoriz@2x.png
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/icnMoreHoriz.imageset/icnMoreHoriz@3x.png
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/incCheckActive.imageset/Contents.json
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/incCheckActive.imageset/incCheckActive.png
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/incCheckActive.imageset/incCheckActive@2x.png
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/incCheckActive.imageset/incCheckActive@3x.png
  Smeem-iOS/Smeem-iOS/Presentation/ForeignDiary/ForeignDiaryViewController.swift
  Smeem-iOS/Smeem-iOS/Presentation/MyPage/EditNicknameViewController.swift
Labels: 쫑 🎀, Setting

#40 [Feat] #33 - 홈뷰 팝업창 및 마이페이지 버튼 구현
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/icn_mypage.imageset/Contents.json
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/icn_mypage.imageset/icn_mypage.png
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/icn_mypage.imageset/icn_mypage@2x.png
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/icn_mypage.imageset/icn_mypage@3x.png
  Smeem-iOS/Smeem-iOS/Presentation/Home/HomeViewController.swift
Labels: 쭈 🦋, Feat

#50 [Feat] #42 - 오늘의 일기 작성
  Smeem-iOS/Smeem-iOS.xcodeproj/project.pbxproj
  Smeem-iOS/Smeem-iOS/Global/Extensions/UIViewController+.swift
  Smeem-iOS/Smeem-iOS/Global/Literals/ConstantImage.swift
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/icnMypage.imageset/Contents.json
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/icnMypage.imageset/icn_mypage.png
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/icnMypage.imageset/icn_mypage@2x.png
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/icnMypage.imageset/icn_mypage@3x.png
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/icnRightArrow.imageset/Contents.json
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/icnRightArrow.imageset/rightArrow.png
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/icnRightArrow.imageset/rightArrow@2x.png
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/icnRightArrow.imageset/rightArrow@3x.png
  Smeem-iOS/Smeem-iOS/Presentation/Home/CalendarCell.swift
  Smeem-iOS/Smeem-iOS/Presentation/Home/HomeViewController.swift
  Smeem-iOS/Smeem-iOS/Presentation/Home/HomeViewFloatingViewController.swift
Labels: 쭈 🦋, Feat

#60 [Feat] #57 - ErrorToastMesssage UI구현 및 SmeemToastView 분기처리
  Smeem-iOS/Smeem-iOS.xcodeproj/project.pbxproj
  Smeem-iOS/Smeem-iOS/Global/UIComponents/CustomToastView.swift
  Smeem-iOS/Smeem-iOS/Global/UIComponents/SmeemToastView.swift
  Smeem-iOS/Smeem-iOS/Presentation/ForeignDiary/DiaryViewController.swift
  Smeem-iOS/Smeem-iOS/Presentation/ForeignDiary/ForeignDiaryViewController.swift
Labels: 쭌 🍆

#65 [Feat] #58 - inputTextView 자동 스크롤 기능 구현
  Smeem-iOS/Smeem-iOS/Presentation/ForeignDiary/DiaryViewController.swift
Labels: 쭌 🍆, Feat

#71 [Feat] #66 - RandomSubject, GetDiary, PostDiary, GetDetailDiary, PapagoAPI 구현
  Smeem-iOS/Smeem-iOS.xcodeproj/project.pbxproj
  Smeem-iOS/Smeem-iOS/Global/UIComponents/DiaryScrollerView.swift
  Smeem-iOS/Smeem-iOS/Global/UIComponents/RandomSubjectView.swift
  Smeem-iOS/Smeem-iOS/Network/API/DetailDiary/DetailDiaryAPI.swift
  Smeem-iOS/Smeem-iOS/Network/API/DetailDiary/DetailDiaryService.swift
  Smeem-iOS/Smeem-iOS/Network/API/Papago/PapagoAPI.swift
  Smeem-iOS/Smeem-iOS/Network/API/Papago/PapagoService.swift
  Smeem-iOS/Smeem-iOS/Network/API/PostDiary/PostDiaryAPI.swift
  Smeem-iOS/Smeem-iOS/Network/API/PostDiary/PostDiaryService.swift
  Smeem-iOS/Smeem-iOS/Network/API/RandomSubject/RandomSubjectAPI.swift
  Smeem-iOS/Smeem-iOS/Network/API/RandomSubject/RandomSubjectService.swift
  Smeem-iOS/Smeem-iOS/Network/API/RandomSubjectAPI.swift
  Smeem-iOS/Smeem-iOS/Network/DataModel/DetailDiary/DetailDiaryResponse.swift
  Smeem-iOS/Smeem-iOS/Network/DataModel/Papago/PapagoResponse.swift
  Smeem-iOS/Smeem-iOS/Network/DataModel/PostDiary/PostDiaryRequest.swift
  Smeem-iOS/Smeem-iOS/Network/DataModel/PostDiary/PostDiaryResponse.swift
  Smeem-iOS/Smeem-iOS/Network/DataModel/RandomSubject/RandomSubjectResponse.swift
  Smeem-iOS/Smeem-iOS/Presentation/DetailDiary/DetailDiaryViewController.swift
  Smeem-iOS/Smeem-iOS/Presentation/ForeignDiary/DiaryStrategies.swift
  Smeem-iOS/Smeem-iOS/Presentation/ForeignDiary/DiaryViewController.swift
  Smeem-iOS/Smeem-iOS/Presentation/ForeignDiary/ForeignDiaryViewController.swift
  Smeem-iOS/Smeem-iOS/Presentation/ForeignDiary/StepTwoKoreanDiaryViewController.swift
Labels: 쭌 🍆, Feat

#72 [Feat] #70 - 홈뷰 API 연결
  Smeem-iOS/Smeem-iOS.xcodeproj/project.pbxproj
  Smeem-iOS/Smeem-iOS/Global/Extensions/Date+.swift
  Smeem-iOS/Smeem-iOS/Global/Extensions/String+.swift
  Smeem-iOS/Smeem-iOS/Network/API/HomeAPI.swift
  Smeem-iOS/Smeem-iOS/Network/DataModel/HomeDiaryResponse.swift
  Smeem-iOS/Smeem-iOS/Network/Service/HomeService.swift
  Smeem-iOS/Smeem-iOS/Presentation/BottomSheet/BottomSheetViewController.swift
  Smeem-iOS/Smeem-iOS/Presentation/Home/HomeViewController.swift
Labels: 쭈 🦋, Feat

#74 [Feat] #73 - 홈뷰와 다른뷰간 화면 전환 구현
  Smeem-iOS/Smeem-iOS/Global/Extensions/String+.swift
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/icnMypage.imageset/Contents.json
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/icnMypage.imageset/icnMypage.png
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/icnMypage.imageset/icnMypage@2x.png
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/icnMypage.imageset/icnMypage@3x.png
  Smeem-iOS/Smeem-iOS/Network/API/DetailDiary/DetailDiaryAPI.swift
  Smeem-iOS/Smeem-iOS/Network/API/DetailDiary/DetailDiaryService.swift
  Smeem-iOS/Smeem-iOS/Presentation/DetailDiary/DetailDiaryViewController.swift
  Smeem-iOS/Smeem-iOS/Presentation/ForeignDiary/DiaryViewController.swift
  Smeem-iOS/Smeem-iOS/Presentation/Home/HomeViewController.swift
  Smeem-iOS/Smeem-iOS/Presentation/Home/HomeViewFloatingViewController.swift
Labels: 쭈 🦋, Feat

#79 [Feat] #75 - 마이페이지 구현 및 서버 연결
  Smeem-iOS/Smeem-iOS.xcodeproj/project.pbxproj
  Smeem-iOS/Smeem-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Smeem-iOS/Smeem-iOS/Global/Constants/Image.swift
  Smeem-iOS/Smeem-iOS/Global/Extensions/UIViewController+.swift
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/btnToggleActive.imageset/Contents.json
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/btnToggleActive.imageset/btnToggleActive.png
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/btnToggleActive.imageset/btnToggleActive@2x.png
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/btnToggleActive.imageset/btnToggleActive@3x.png
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/btnToggleInActive.imageset/Contents.json
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/btnToggleInActive.imageset/btnToggleInActive.png
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/btnToggleInActive.imageset/btnToggleInActive@2x.png
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/btnToggleInActive.imageset/btnToggleInActive@3x.png
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/icnMoreMono.imageset/Contents.json
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/icnMoreMono.imageset/icnMoreMono.png
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/icnMoreMono.imageset/icnMoreMono@2x.png
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/icnMoreMono.imageset/icnMoreMono@3x.png
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/icnPencil.imageset/Contents.json
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/icnPencil.imageset/icnPencil.png
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/icnPencil.imageset/icnPencil@2x.png
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/icnPencil.imageset/icnPencil@3x.png
  Smeem-iOS/Smeem-iOS/Network/API/Home/HomeAPI.swift
  Smeem-iOS/Smeem-iOS/Network/API/Home/HomeService.swift
  Smeem-iOS/Smeem-iOS/Network/API/MyPage/MyPageAPI.swift
  Smeem-iOS/Smeem-iOS/Network/API/MyPage/MyPageService.swift
  Smeem-iOS/Smeem-iOS/Network/DataModel/DataModel.swift
  Smeem-iOS/Smeem-iOS/Network/DataModel/MyPageInfoResponse.swift
  Smeem-iOS/Smeem-iOS/Presentation/DetailDiary/DetailDiaryViewController.swift
  Smeem-iOS/Smeem-iOS/Presentation/ForeignDiary/DiaryViewController.swift
  Smeem-iOS/Smeem-iOS/Presentation/ForeignDiary/ForeignDiaryViewController.swift
  Smeem-iOS/Smeem-iOS/Presentation/Home/HomeViewController.swift
  Smeem-iOS/Smeem-iOS/Presentation/MyPage/EditNicknameViewController.swift
  Smeem-iOS/Smeem-iOS/Presentation/MyPage/MyPageViewController.swift
  Smeem-iOS/Smeem-iOS/Presentation/Onboarding/Goal/GoalCollectionViewCell.swift
Labels: 쭈 🦋, Feat

#81 [Chore] #77 - Qa 반영
  Smeem-iOS/Smeem-iOS.xcodeproj/project.pbxproj
  Smeem-iOS/Smeem-iOS/Global/Constants/Image.swift
  Smeem-iOS/Smeem-iOS/Global/Protocols/DataBindProtocol.swift
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/btnRandomSubjectActive.imageset/Contents.json
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/btnRandomSubjectActive.imageset/RandomSubjectActive.png
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/btnRandomSubjectActive.imageset/RandomSubjectActive@2x.png
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/btnRandomSubjectActive.imageset/RandomSubjectActive@3x.png
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/btnRandomSubjectEnabled.imageset/Contents.json
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/btnRandomSubjectEnabled.imageset/Group 34101.png
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/btnRandomSubjectEnabled.imageset/Group 34101@2x.png
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/btnRandomSubjectEnabled.imageset/Group 34101@3x.png
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/btnRandomSubjectInactive.imageset/Contents.json
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/btnRandomSubjectInactive.imageset/RandomSubjectInactive.png
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/btnRandomSubjectInactive.imageset/RandomSubjectInactive@2x.png
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/btnRandomSubjectInactive.imageset/RandomSubjectInactive@3x.png
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/btnTranslateActive.imageset/Contents.json
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/btnTranslateActive.imageset/btnTranslate-1.png
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/btnTranslateActive.imageset/btnTranslate@2x-1.png
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/btnTranslateActive.imageset/btnTranslate@3x-1.png
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/btnTranslateInactive.imageset/Contents.json
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/btnTranslateInactive.imageset/btnTranslate.png
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/btnTranslateInactive.imageset/btnTranslate@2x.png
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/btnTranslateInactive.imageset/btnTranslate@3x.png
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/icnRefresh.imageset/Contents.json
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/icnRefresh.imageset/icon-refresh-mono.png
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/icnRefresh.imageset/icon-refresh-mono@2x.png
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/icnRefresh.imageset/icon-refresh-mono@3x.png
  Smeem-iOS/Smeem-iOS/Global/UIComponents/RandomSubjectView.swift
  Smeem-iOS/Smeem-iOS/Global/UIComponents/SmeemToastView.swift
  Smeem-iOS/Smeem-iOS/Presentation/DetailDiary/DetailDiaryViewController.swift
  Smeem-iOS/Smeem-iOS/Presentation/ForeignDiary/DiaryStrategies.swift
  Smeem-iOS/Smeem-iOS/Presentation/ForeignDiary/DiaryViewController.swift
  Smeem-iOS/Smeem-iOS/Presentation/ForeignDiary/ForeignDiaryViewController.swift
  Smeem-iOS/Smeem-iOS/Presentation/ForeignDiary/StepOneKoreanDiaryViewController.swift
  Smeem-iOS/Smeem-iOS/Presentation/ForeignDiary/StepTwoKoreanDiaryViewController.swift
Labels: 쭌 🍆, Chore

#86 [Feat] #83 - badge popup 및 랜덤 주제 포함한 일기 상세 UI
  Smeem-iOS/Smeem-iOS.xcodeproj/project.pbxproj
  Smeem-iOS/Smeem-iOS/Global/Constants/Image.swift
  Smeem-iOS/Smeem-iOS/Global/Constants/UserDefaultsManager.swift
  Smeem-iOS/Smeem-iOS/Global/Literals/ColorLiterals.swift
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/Badge/colorWelcomeBadge.imageset/Contents.json
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/Badge/colorWelcomeBadge.imageset/welcome.png
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/Badge/colorWelcomeBadge.imageset/welcome@2x.png
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/Badge/colorWelcomeBadge.imageset/welcome@3x.png
  Smeem-iOS/Smeem-iOS/Global/UIComponents/Alarm/AlarmCollectionView.swift
  Smeem-iOS/Smeem-iOS/Global/UIComponents/Alarm/DatePickerFooterView.swift
  Smeem-iOS/Smeem-iOS/Global/UIComponents/Diary/DiaryDetailRandomSubjectView.swift
  Smeem-iOS/Smeem-iOS/Global/UIComponents/Diary/DiaryScrollerView.swift
  Smeem-iOS/Smeem-iOS/Global/UIComponents/Diary/RandomSubjectView.swift
  Smeem-iOS/Smeem-iOS/Global/UIComponents/Diary/SeparationLine.swift
  Smeem-iOS/Smeem-iOS/Global/UIComponents/Onboarding/HowLearningView.swift
  Smeem-iOS/Smeem-iOS/Global/UIComponents/SmeemComponent/SmeemButton.swift
  Smeem-iOS/Smeem-iOS/Global/UIComponents/SmeemComponent/SmeemToastView.swift
  Smeem-iOS/Smeem-iOS/Network/API/PostDiary/PostDiaryAPI.swift
  Smeem-iOS/Smeem-iOS/Network/DataModel/PostDiary/PostDiaryResponse.swift
  Smeem-iOS/Smeem-iOS/Presentation/BadgePopup/BadgePopupViewController.swift
  Smeem-iOS/Smeem-iOS/Presentation/DetailDiary/DetailDiaryViewController.swift
  Smeem-iOS/Smeem-iOS/Presentation/ForeignDiary/DiaryViewController.swift
  Smeem-iOS/Smeem-iOS/Presentation/ForeignDiary/ForeignDiaryViewController.swift
  Smeem-iOS/Smeem-iOS/Presentation/Home/HomeViewController.swift
  Smeem-iOS/Smeem-iOS/Presentation/MyPage/BadgeList/VC/BadgeListViewController.swift
  Smeem-iOS/Smeem-iOS/Presentation/MyPage/BadgeList/View/DetailBadgeCollectionViewCell.swift
  Smeem-iOS/Smeem-iOS/Presentation/MyPage/MyPage/MyPageViewController.swift
  Smeem-iOS/Smeem-iOS/Presentation/Onboarding/Alarm/VC/AlarmSettingViewController.swift
  Smeem-iOS/Smeem-iOS/Presentation/Onboarding/Nickname/UserNickNameViewController.swift
  Smeem-iOS/Smeem-iOS/Supports/SceneDelegate.swift
Labels: 짠 ✨, Feat
