Repository Team-Smeme/Smeem-iOS, pull requests merged in 2023-08, with the labels that each got.

#105 [Chore] #103 - onboarding flow 변경
  Smeem-iOS/Smeem-iOS.xcodeproj/project.pbxproj
  Smeem-iOS/Smeem-iOS/Global/Constants/Image.swift
  Smeem-iOS/Smeem-iOS/Global/Extensions/UICollectionViewCell+.swift
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/icnForward.imageset/Contents.json
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/icnForward.imageset/icnForward.png
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/icnForward.imageset/icnForward@2x.png
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/icnForward.imageset/icnForward@3x.png
  Smeem-iOS/Smeem-iOS/Global/UIComponents/Alarm/AlarmCollectionView.swift
  Smeem-iOS/Smeem-iOS/Presentation/BottomSheet/VC/BottomSheetView.swift
  Smeem-iOS/Smeem-iOS/Presentation/BottomSheet/VC/BottomSheetViewController.swift
  Smeem-iOS/Smeem-iOS/Presentation/Onboarding/Alarm/VC/AlarmSettingViewController.swift
  Smeem-iOS/Smeem-iOS/Presentation/Onboarding/How/VC/HowOnboardingViewController.swift
  Smeem-iOS/Smeem-iOS/Presentation/Onboarding/Nickname/UserNickNameViewController.swift
  Smeem-iOS/Smeem-iOS/Presentation/Onboarding/Service/ServiceAcceptCollectionViewCell.swift
  Smeem-iOS/Smeem-iOS/Presentation/Onboarding/Service/ServiceAcceptTotalCollectionViewCell.swift
  Smeem-iOS/Smeem-iOS/Presentation/Onboarding/Service/ServiceAcceptViewController.swift
  Smeem-iOS/Smeem-iOS/Presentation/Splash/SplashViewController.swift
Labels: 짠 ✨, Chore

#112 [Chore] #109 edit goal
  Smeem-iOS/Smeem-iOS.xcodeproj/project.pbxproj
  Smeem-iOS/Smeem-iOS/Global/Extensions/UIViewController+.swift
  Smeem-iOS/Smeem-iOS/Global/Protocols/NextButtonDelegate.swift
  Smeem-iOS/Smeem-iOS/Global/UIComponents/Diary/DiaryScrollerView.swift
  Smeem-iOS/Smeem-iOS/Global/UIComponents/Onboarding/HowLearningView.swift
  Smeem-iOS/Smeem-iOS/Global/UIComponents/SmeemComponent/SmeemToastView.swift
  Smeem-iOS/Smeem-iOS/Presentation/ForeignDiary/DiaryStrategies.swift
  Smeem-iOS/Smeem-iOS/Presentation/ForeignDiary/DiaryViewController.swift
  Smeem-iOS/Smeem-iOS/Presentation/ForeignDiary/StepOneKoreanDiaryViewController.swift
  Smeem-iOS/Smeem-iOS/Presentation/ForeignDiary/StepTwoKoreanDiaryViewController.swift
  Smeem-iOS/Smeem-iOS/Presentation/MyPage/EditGoal/EditGoalViewController.swift
  Smeem-iOS/Smeem-iOS/Presentation/MyPage/MyPage/MyPageViewController.swift
  Smeem-iOS/Smeem-iOS/Presentation/Onboarding/Goal/DataSource/GoalCollectionViewDataSource.swift
  Smeem-iOS/Smeem-iOS/Presentation/Onboarding/Goal/VC/GoalViewController.swift
  Smeem-iOS/Smeem-iOS/Presentation/Onboarding/Goal/View/Cell/GoalCollectionViewCell.swift
  Smeem-iOS/Smeem-iOS/Presentation/Onboarding/Goal/View/GoalEditMypageView.swift
  Smeem-iOS/Smeem-iOS/Presentation/Onboarding/Goal/View/GoalOnboardingView.swift
  Smeem-iOS/Smeem-iOS/Presentation/Splash/SmeemStartViewController.swift
  Smeem-iOS/Smeem-iOS/Presentation/Splash/SplashViewController.swift
Labels: 쭌 🍆, Chore

#114 [Feat] #111 - 마이페이지 목표 설정, 알림 설정 로직 구현
  Smeem-iOS/Smeem-iOS.xcodeproj/project.pbxproj
  Smeem-iOS/Smeem-iOS/Global/UIComponents/Alarm/AlarmCollectionView.swift
  Smeem-iOS/Smeem-iOS/Global/UIComponents/Alarm/DatePickerFooterView.swift
  Smeem-iOS/Smeem-iOS/Network/API/Auth/AuthAPI.swift
  Smeem-iOS/Smeem-iOS/Presentation/BottomSheet/VC/BottomSheetViewController.swift
  Smeem-iOS/Smeem-iOS/Presentation/MyPage/AuthManagement/AuthManagementViewController.swift
  Smeem-iOS/Smeem-iOS/Presentation/MyPage/EditAlarm/EditAlarmViewController.swift
  Smeem-iOS/Smeem-iOS/Presentation/MyPage/EditGoal/EditGoalViewController.swift
  Smeem-iOS/Smeem-iOS/Presentation/MyPage/MyPage/MyPageViewController.swift
  Smeem-iOS/Smeem-iOS/Presentation/Onboarding/Goal/DataSource/GoalCollectionViewDataSource.swift
  Smeem-iOS/Smeem-iOS/Presentation/Onboarding/Goal/VC/GoalViewController.swift
  Smeem-iOS/Smeem-iOS/Presentation/Onboarding/Goal/View/Cell/GoalCollectionViewCell.swift
  Smeem-iOS/Smeem-iOS/Presentation/Onboarding/Service/ServiceAcceptViewController.swift
  Smeem-iOS/Smeem-iOS/Presentation/Splash/SplashViewController.swift
Labels: 짠 ✨, Feat

#113 [Fix] #102 - 홈 캘린더 레이아웃 수정
  Smeem-iOS/Smeem-iOS/Presentation/Home/CalendarCell.swift
  Smeem-iOS/Smeem-iOS/Presentation/Home/HomeViewController.swift
Labels: 쭈 🦋, Fix

#120 [Chore] #119 - placeholder라벨 원상복구
  Smeem-iOS/Smeem-iOS/Presentation/ForeignDiary/DiaryViewController.swift
Labels: 쭌 🍆, Chore
