Repository Team-Smeme/Smeem-iOS, pull requests merged in 2023-07, with the labels that each got.

#89 [Feat] #62 - 온보딩 API
  Smeem-iOS/Smeem-iOS.xcodeproj/project.pbxproj
  Smeem-iOS/Smeem-iOS/Global/UIComponents/Onboarding/HowLearningView.swift
  Smeem-iOS/Smeem-iOS/Network/API/Auth/AuthService.swift
  Smeem-iOS/Smeem-iOS/Network/API/Onboarding/OnboardingAPI.swift
  Smeem-iOS/Smeem-iOS/Network/API/Onboarding/OnboardingService.swift
  Smeem-iOS/Smeem-iOS/Network/Base/NetworkHeader.swift
  Smeem-iOS/Smeem-iOS/Network/Base/URLConstant.swift
  Smeem-iOS/Smeem-iOS/Presentation/BottomSheet/VC/BottomSheetViewController.swift
  Smeem-iOS/Smeem-iOS/Presentation/Home/HomeViewController.swift
  Smeem-iOS/Smeem-iOS/Presentation/MyPage/MyPage/MyPageViewController.swift
  Smeem-iOS/Smeem-iOS/Presentation/Onboarding/Alarm/VC/AlarmSettingViewController.swift
  Smeem-iOS/Smeem-iOS/Presentation/Onboarding/Goal/Model/PlanListResponse.swift
  Smeem-iOS/Smeem-iOS/Presentation/Onboarding/Goal/VC/GoalOnboardingViewController.swift
  Smeem-iOS/Smeem-iOS/Presentation/Onboarding/Goal/View/GoalCollectionViewCell.swift
  Smeem-iOS/Smeem-iOS/Presentation/Onboarding/How/Model/DetailPlanListResponse.swift
  Smeem-iOS/Smeem-iOS/Presentation/Onboarding/How/VC/HowOnboardingViewController.swift
  Smeem-iOS/Smeem-iOS/Presentation/Onboarding/Nickname/UserNickNameViewController.swift
Labels: 짠 ✨, Feat

#91 [Feat] #98 - 베타 테스트 버전 로그인 API 수정사항에 맞게 모델 변경 및 플로우 수정
  Smeem-iOS/Smeem-iOS/Global/Constants/UserDefaultsManager.swift
  Smeem-iOS/Smeem-iOS/Global/UIComponents/Diary/DiaryDetailRandomSubjectView.swift
  Smeem-iOS/Smeem-iOS/Network/API/Auth/AuthAPI.swift
  Smeem-iOS/Smeem-iOS/Network/API/Auth/AuthService.swift
  Smeem-iOS/Smeem-iOS/Network/DataModel/MyPageInfoResponse.swift
  Smeem-iOS/Smeem-iOS/Presentation/BottomSheet/Model/AuthModel.swift
  Smeem-iOS/Smeem-iOS/Presentation/BottomSheet/VC/BottomSheetViewController.swift
  Smeem-iOS/Smeem-iOS/Presentation/Home/HomeViewController.swift
  Smeem-iOS/Smeem-iOS/Presentation/MyPage/MyPage/MyPageViewController.swift
  Smeem-iOS/Smeem-iOS/Presentation/Onboarding/Nickname/UserNickNameViewController.swift
  Smeem-iOS/Smeem-iOS/Supports/AppDelegate.swift
Labels: 짠 ✨, Feat

#85 [Chore] #77 - qa2
  Smeem-iOS/Smeem-iOS/Global/UIComponents/Diary/RandomSubjectView.swift
  Smeem-iOS/Smeem-iOS/Global/UIComponents/SmeemComponent/SmeemToastView.swift
  Smeem-iOS/Smeem-iOS/Presentation/ForeignDiary/DiaryViewController.swift
  Smeem-iOS/Smeem-iOS/Presentation/ForeignDiary/ForeignDiaryViewController.swift
  Smeem-iOS/Smeem-iOS/Presentation/ForeignDiary/StepOneKoreanDiaryViewController.swift
  Smeem-iOS/Smeem-iOS/Presentation/ForeignDiary/StepTwoKoreanDiaryViewController.swift
  Smeem-iOS/Smeem-iOS/Presentation/Home/HomeViewFloatingViewController.swift
Labels: 쭌 🍆, Chore

#88 [Feat] #87 - 일기 삭제 API 연결
  Smeem-iOS/Smeem-iOS/Network/API/DetailDiary/DetailDiaryAPI.swift
  Smeem-iOS/Smeem-iOS/Network/API/DetailDiary/DetailDiaryService.swift
  Smeem-iOS/Smeem-iOS/Presentation/DetailDiary/DetailDiaryViewController.swift
Labels: 쭈 🦋, Feat

#94 [Feat] #98 - QA 반영
  Smeem-iOS/Smeem-iOS.xcodeproj/project.pbxproj
  Smeem-iOS/Smeem-iOS/Global/Constants/Image.swift
  Smeem-iOS/Smeem-iOS/Global/Constants/UserDefaultsManager.swift
  Smeem-iOS/Smeem-iOS/Global/Extensions/UIViewController+.swift
  Smeem-iOS/Smeem-iOS/Global/Literals/FontLiterals.swift
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/icnToolTip.imageset/Contents.json
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/icnToolTip.imageset/toolTip.png
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/icnToolTip.imageset/toolTip@2x.png
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/icnToolTip.imageset/toolTip@3x.png
  Smeem-iOS/Smeem-iOS/Global/Resources/Fonts/Urbanist-SemiBold.otf
  Smeem-iOS/Smeem-iOS/Global/UIComponents/Alarm/AlarmCollectionView.swift
  Smeem-iOS/Smeem-iOS/Global/UIComponents/Alarm/AlarmCollectionViewCell.swift
  Smeem-iOS/Smeem-iOS/Global/UIComponents/Alarm/DatePickerFooterView.swift
  Smeem-iOS/Smeem-iOS/Global/UIComponents/Diary/DiaryScrollerView.swift
  Smeem-iOS/Smeem-iOS/Info.plist
  Smeem-iOS/Smeem-iOS/Network/API/DetailDiary/DetailDiaryAPI.swift
  Smeem-iOS/Smeem-iOS/Network/API/Papago/PapagoService.swift
  Smeem-iOS/Smeem-iOS/Network/API/PostDiary/PostDiaryAPI.swift
  Smeem-iOS/Smeem-iOS/Network/API/PostDiary/PostDiaryService.swift
  Smeem-iOS/Smeem-iOS/Network/API/Push/PushTestAPI.swift
  Smeem-iOS/Smeem-iOS/Network/API/Push/PushTestService.swift
  Smeem-iOS/Smeem-iOS/Network/Base/URLConstant.swift
  Smeem-iOS/Smeem-iOS/Network/DataModel/PatchDiary/PatchDiaryRequest.swift
  Smeem-iOS/Smeem-iOS/Presentation/BadgePopup/BadgePopupViewController.swift
  Smeem-iOS/Smeem-iOS/Presentation/DetailDiary/DetailDiaryViewController.swift
  Smeem-iOS/Smeem-iOS/Presentation/ForeignDiary/DiaryStrategies.swift
  Smeem-iOS/Smeem-iOS/Presentation/ForeignDiary/DiaryViewController.swift
  Smeem-iOS/Smeem-iOS/Presentation/ForeignDiary/EditDiaryViewController.swift
  Smeem-iOS/Smeem-iOS/Presentation/ForeignDiary/ForeignDiaryViewController.swift
  Smeem-iOS/Smeem-iOS/Presentation/ForeignDiary/StepOneKoreanDiaryViewController.swift
  Smeem-iOS/Smeem-iOS/Presentation/ForeignDiary/StepTwoKoreanDiaryViewController.swift
  Smeem-iOS/Smeem-iOS/Presentation/Home/HomeViewController.swift
  Smeem-iOS/Smeem-iOS/Presentation/LodingView/LoadingView.swift
  Smeem-iOS/Smeem-iOS/Presentation/MyPage/EditNickname/EditNicknameViewController.swift
  Smeem-iOS/Smeem-iOS/Presentation/MyPage/MyPage/MyPageViewController.swift
  Smeem-iOS/Smeem-iOS/Presentation/Onboarding/Alarm/VC/AlarmSettingViewController.swift
  Smeem-iOS/Smeem-iOS/Presentation/Onboarding/Goal/View/GoalCollectionViewCell.swift
  Smeem-iOS/Smeem-iOS/Presentation/Onboarding/How/VC/HowOnboardingViewController.swift
  Smeem-iOS/Smeem-iOS/Presentation/Onboarding/Nickname/UserNickNameViewController.swift
  Smeem-iOS/Smeem-iOS/Presentation/Splash/SplashViewController.swift
  Smeem-iOS/Smeem-iOS/Supports/AppDelegate.swift
Labels: Feat

#100 [Chore] #98 - QA 반영
  Smeem-iOS/Smeem-iOS.xcodeproj/project.pbxproj
  Smeem-iOS/Smeem-iOS/Presentation/MyPage/MyPage/MyPageViewController.swift
  Smeem-iOS/Smeem-iOS/Presentation/Onboarding/Nickname/UserNickNameViewController.swift
Labels: 짠 ✨, Chore

#99 [Fix] #98 - 홈뷰 이슈 해결
  Smeem-iOS/Smeem-iOS/Presentation/DetailDiary/DetailDiaryViewController.swift
  Smeem-iOS/Smeem-iOS/Presentation/Home/HomeViewController.swift
Labels: 쭈 🦋, Fix
