Repository Team-Smeme/Smeem-iOS, pull requests merged in 2023-09, with the labels that each got.

#128 [Chore] #125 - 토스트뷰 생성 메서드 익스텐션화
  Smeem-iOS/Smeem-iOS/Global/Extensions/UIViewController+.swift
  Smeem-iOS/Smeem-iOS/Presentation/ForeignDiary/DiaryViewController.swift
  Smeem-iOS/Smeem-iOS/Presentation/Home/HomeViewController.swift
  Smeem-iOS/Smeem-iOS/Presentation/MyPage/MyPage/MyPageViewController.swift
  Smeem-iOS/Smeem-iOS/Presentation/Onboarding/Alarm/VC/AlarmSettingViewController.swift
Labels: Chore

#132 [Feat] #130 홈뷰 버튼 터치영역 크기 수정
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/icnMyPage.imageset/Contents.json
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/icnMyPage.imageset/icnMyPage.png
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/icnMyPage.imageset/icnMyPage@2x.png
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/icnMyPage.imageset/icnMyPage@3x.png
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/icnRightArrow.imageset/Contents.json
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/icnRightArrow.imageset/icnRightArrow.png
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/icnRightArrow.imageset/icnRightArrow@2x.png
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/icnRightArrow.imageset/icnRightArrow@3x.png
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/icnRightArrow.imageset/rightArrow@2x.png
  Smeem-iOS/Smeem-iOS/Presentation/Home/HomeViewController.swift
  Smeem-iOS/Smeem-iOS/Presentation/Home/HomeViewFloatingViewController.swift
Labels: 쭈 🦋, Feat

#140 [Feat] #133 - 강제 업데이트 기능 구현
  Smeem-iOS/Smeem-iOS.xcodeproj/project.pbxproj
  Smeem-iOS/Smeem-iOS/Global/Constants/System.swift
  Smeem-iOS/Smeem-iOS/Global/UIComponents/Alarm/DatePickerFooterView.swift
  Smeem-iOS/Smeem-iOS/Global/UIComponents/Onboarding/HowLearningView.swift
  Smeem-iOS/Smeem-iOS/Info.plist
  Smeem-iOS/Smeem-iOS/Network/Base/BaseTargetType.swift
  Smeem-iOS/Smeem-iOS/Network/Base/SharedConstant.swift
  Smeem-iOS/Smeem-iOS/Presentation/BottomSheet/VC/BottomSheetView.swift
  Smeem-iOS/Smeem-iOS/Presentation/ForeignDiary/DiaryStrategies.swift
  Smeem-iOS/Smeem-iOS/Presentation/MyPage/AuthManagement/AuthManagementViewController.swift
  Smeem-iOS/Smeem-iOS/Presentation/MyPage/BadgeList/VC/BadgeListViewController.swift
  Smeem-iOS/Smeem-iOS/Presentation/MyPage/EditAlarm/EditAlarmViewController.swift
  Smeem-iOS/Smeem-iOS/Presentation/MyPage/EditGoal/EditGoalViewController.swift
  Smeem-iOS/Smeem-iOS/Presentation/MyPage/EditNickname/EditNicknameViewController.swift
  Smeem-iOS/Smeem-iOS/Presentation/MyPage/MyPage/MyPageViewController.swift
  Smeem-iOS/Smeem-iOS/Presentation/Onboarding/Alarm/VC/AlarmSettingViewController.swift
  Smeem-iOS/Smeem-iOS/Presentation/Onboarding/Goal/VC/GoalViewController.swift
  Smeem-iOS/Smeem-iOS/Presentation/Onboarding/Goal/View/Cell/GoalCollectionViewCell.swift
  Smeem-iOS/Smeem-iOS/Presentation/Onboarding/How/VC/HowOnboardingViewController.swift
  Smeem-iOS/Smeem-iOS/Presentation/Onboarding/Service/ServiceAcceptCollectionViewCell.swift
  Smeem-iOS/Smeem-iOS/Presentation/Onboarding/Service/ServiceAcceptViewController.swift
  Smeem-iOS/Smeem-iOS/Presentation/Splash/SmeemStartViewController.swift
  Smeem-iOS/Smeem-iOS/Presentation/Splash/SplashViewController.swift
Labels: 짠 ✨, Feat

#141 [Release] 2.0.0 버전 업데이트
  Smeem-iOS/Smeem-iOS.xcodeproj/project.pbxproj
  Smeem-iOS/Smeem-iOS/Global/Constants/System.swift
  Smeem-iOS/Smeem-iOS/Global/Extensions/UITextView+.swift
  Smeem-iOS/Smeem-iOS/Global/Extensions/UIViewController+.swift
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/icnMyPage.imageset/Contents.json
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/icnMyPage.imageset/icnMyPage.png
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/icnMyPage.imageset/icnMyPage@2x.png
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/icnMyPage.imageset/icnMyPage@3x.png
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/icnRightArrow.imageset/Contents.json
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/icnRightArrow.imageset/icnRightArrow.png
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/icnRightArrow.imageset/icnRightArrow@2x.png
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/icnRightArrow.imageset/icnRightArrow@3x.png
  Smeem-iOS/Smeem-iOS/Global/Resources/Assets.xcassets/icnRightArrow.imageset/rightArrow@2x.png
  Smeem-iOS/Smeem-iOS/Global/UIComponents/Alarm/DatePickerFooterView.swift
  Smeem-iOS/Smeem-iOS/Global/UIComponents/Onboarding/HowLearningView.swift
  Smeem-iOS/Smeem-iOS/Info.plist
  Smeem-iOS/Smeem-iOS/Network/Base/BaseTargetType.swift
  Smeem-iOS/Smeem-iOS/Network/Base/SharedConstant.swift
  Smeem-iOS/Smeem-iOS/Presentation/BottomSheet/VC/BottomSheetView.swift
  Smeem-iOS/Smeem-iOS/Presentation/DetailDiary/DetailDiaryViewController.swift
  Smeem-iOS/Smeem-iOS/Presentation/ForeignDiary/DiaryStrategies.swift
  Smeem-iOS/Smeem-iOS/Presentation/ForeignDiary/DiaryViewController.swift
  Smeem-iOS/Smeem-iOS/Presentation/ForeignDiary/EditDiaryViewController.swift
  Smeem-iOS/Smeem-iOS/Presentation/ForeignDiary/StepTwoKoreanDiaryViewController.swift
  Smeem-iOS/Smeem-iOS/Presentation/Home/HomeViewController.swift
  Smeem-iOS/Smeem-iOS/Presentation/Home/HomeViewFloatingViewController.swift
  Smeem-iOS/Smeem-iOS/Presentation/MyPage/AuthManagement/AuthManagementViewController.swift
  Smeem-iOS/Smeem-iOS/Presentation/MyPage/BadgeList/VC/BadgeListViewController.swift
  Smeem-iOS/Smeem-iOS/Presentation/MyPage/EditAlarm/EditAlarmViewController.swift
  Smeem-iOS/Smeem-iOS/Presentation/MyPage/EditGoal/EditGoalViewController.swift
  Smeem-iOS/Smeem-iOS/Presentation/MyPage/EditNickname/EditNicknameViewController.swift
  Smeem-iOS/Smeem-iOS/Presentation/MyPage/MyPage/MyPageViewController.swift
  Smeem-iOS/Smeem-iOS/Presentation/Onboarding/Alarm/VC/AlarmSettingViewController.swift
  Smeem-iOS/Smeem-iOS/Presentation/Onboarding/Goal/VC/GoalViewController.swift
  Smeem-iOS/Smeem-iOS/Presentation/Onboarding/Goal/View/Cell/GoalCollectionViewCell.swift
  Smeem-iOS/Smeem-iOS/Presentation/Onboarding/How/VC/HowOnboardingViewController.swift
  Smeem-iOS/Smeem-iOS/Presentation/Onboarding/Service/ServiceAcceptCollectionViewCell.swift
  Smeem-iOS/Smeem-iOS/Presentation/Onboarding/Service/ServiceAcceptViewController.swift
  Smeem-iOS/Smeem-iOS/Presentation/Splash/SmeemStartViewController.swift
  Smeem-iOS/Smeem-iOS/Presentation/Splash/SplashViewController.swift
Labels: 짠 ✨

#134 [Refactor] #126 - SmeemNavigationBar 컴포넌트화
  Smeem-iOS/Smeem-iOS.xcodeproj/project.pbxproj
  Smeem-iOS/Smeem-iOS/Global/Extensions/UIView+.swift
  Smeem-iOS/Smeem-iOS/Global/Extensions/UIViewController+.swift
  Smeem-iOS/Smeem-iOS/Global/UIComponents/SmeemComponent/NavigationBar/NavigationBarActionDelegate.swift
  Smeem-iOS/Smeem-iOS/Global/UIComponents/SmeemComponent/NavigationBar/NavigationBarConfigurationBuilder.swift
  Smeem-iOS/Smeem-iOS/Global/UIComponents/SmeemComponent/NavigationBar/NavigationBarType.swift
  Smeem-iOS/Smeem-iOS/Global/UIComponents/SmeemComponent/NavigationBar/SmeemNavigationBar.swift
  Smeem-iOS/Smeem-iOS/Global/UIComponents/SmeemComponent/NavigationBar/SmeemNavigationFactory.swift
  Smeem-iOS/Smeem-iOS/Presentation/DetailDiary/DetailDiaryViewController.swift
Labels: 쭌 🍆, Refactor
