Repository Team-Smeme/Smeem-iOS, pull requests merged in 2024-12, with the labels that each got.

#230 [Feat] #229 Coaching Service 구현 및 테스트 코드 작성
  .github/workflows/smeemDev.yml
  Smeem-iOS/Smeem-iOS.xcodeproj/project.pbxproj
  Smeem-iOS/Smeem-iOS/Global/Extensions/MoyaProvier+.swift
  Smeem-iOS/Smeem-iOS/Global/HighlightModifier.swift
  Smeem-iOS/Smeem-iOS/Global/Literals/ColorLiterals.swift
  Smeem-iOS/Smeem-iOS/Global/Protocols/Store.swift
  Smeem-iOS/Smeem-iOS/Global/UIComponents/SwiftUI/CoachingComparisonView.swift
  Smeem-iOS/Smeem-iOS/Global/UIComponents/UIViewConponent/CoachingComparisonView.swift
  Smeem-iOS/Smeem-iOS/Network/API/Coaching/CoachingEndPoint.swift
  Smeem-iOS/Smeem-iOS/Network/API/Coaching/CoachingResponse.swift
  Smeem-iOS/Smeem-iOS/Network/API/Coaching/CoachingService.swift
  Smeem-iOS/Smeem-iOS/Network/API/Coaching/CoachingServiceProtocol.swift
  Smeem-iOS/Smeem-iOS/Network/API/DetailDiary/DetailDiaryEndPoint.swift
  Smeem-iOS/Smeem-iOS/Network/NetworkDataModel/Coaching/CoachingResponse.swift
  Smeem-iOS/Smeem-iOS/Network/NetworkDataModel/DetailDiary/DetailDiaryResponse.swift
  Smeem-iOS/Smeem-iOS/Presentation/Coaching/CoachingCompleteView.swift
  Smeem-iOS/Smeem-iOS/Presentation/Diaries/View/Controllers/ForeignDiaryViewController.swift
  Smeem-iOS/Smeem-iOS/Presentation/Diaries/View/Controllers/StepTwoKoreanDiaryViewController.swift
  Smeem-iOS/Smeem-iOS/Presentation/DiaryComplete/CoachingService.swift
  Smeem-iOS/Smeem-iOS/Presentation/DiaryComplete/CoachingStore.swift
  Smeem-iOS/Smeem-iOS/Presentation/DiaryComplete/CoachingView.swift
  Smeem-iOS/Smeem-iOS/Presentation/DiaryComplete/SmemeToastView.swift
  Smeem-iOS/Smeem-iOS/Presentation/Home/HomeViewController.swift
  Smeem-iOS/Smeem-iOSTests/Coaching/Service/CoachingServiceTest.swift
  Smeem-iOS/Smeem-iOSTests/Onboarding/Mock/OnboardingServiceMock.swift
  Smeem-iOS/Smeem-iOSTests/Onboarding/Service/OnboardingServiceTest.swift
  Smeem-iOS/Smeem-iOSTests/Onboarding/ViewModel/TrainingAlarmViewModelTest.swift
Labels: 짠 ✨, Feat

#236 [Feat] #235 - 코칭 일기 1차 QA
  .github/workflows/smeemDev.yml
  Smeem-iOS/Smeem-iOS.xcodeproj/project.pbxproj
  Smeem-iOS/Smeem-iOS/Global/Extensions/SwiftUI/HighlightModifier.swift
  Smeem-iOS/Smeem-iOS/Global/UIComponents/SmeemComponent/LoadingView/SmemeLoadingView.swift
  Smeem-iOS/Smeem-iOS/Global/UIComponents/SmeemComponent/Toast/SmemeToastView.swift
  Smeem-iOS/Smeem-iOS/Global/UIComponents/SwiftUI/CoachingComparisonView.swift
  Smeem-iOS/Smeem-iOS/Global/UIComponents/UIViewConponent/CoachingCompletedView.swift
  Smeem-iOS/Smeem-iOS/Global/UIComponents/UIViewConponent/CoachingExplanationView.swift
  Smeem-iOS/Smeem-iOS/Global/UIComponents/UIViewConponent/CustomSegmentedControl.swift
  Smeem-iOS/Smeem-iOS/Global/UIComponents/UIViewConponent/SwiftUINavigationView.swift
  Smeem-iOS/Smeem-iOS/Presentation/Coaching/View/CoachingView.swift
  Smeem-iOS/Smeem-iOS/Presentation/Components/CoachingCompleteView.swift
  Smeem-iOS/Smeem-iOS/Presentation/Components/DiaryDetailView.swift
  Smeem-iOS/Smeem-iOS/Presentation/DiaryComplete/CoachingView.swift
  Smeem-iOS/Smeem-iOS/Presentation/Store/CoachingStore.swift
Labels: 짠 ✨, Feat

#238 [Feat] #235 - 일기 첨삭 2차 QA
  Smeem-iOS/Smeem-iOS.xcodeproj/project.pbxproj
  Smeem-iOS/Smeem-iOS/Presentation/Coaching/Components/CoachingCompleteView.swift
  Smeem-iOS/Smeem-iOS/Presentation/Coaching/Components/DiaryDetailView.swift
  Smeem-iOS/Smeem-iOS/Presentation/Coaching/Store/CoachingStore.swift
  Smeem-iOS/Smeem-iOS/Presentation/Coaching/View/CoachingView.swift
  Smeem-iOS/Smeem-iOSTests/Coaching/Store/CoachingStoreTest.swift
Labels: Feat

#242 [Fix] #241 - 코칭 3차 QA
  Smeem-iOS/Smeem-iOS/Global/Extensions/SwiftUI/View+.swift
  Smeem-iOS/Smeem-iOS/Global/Extensions/UIViewController+.swift
  Smeem-iOS/Smeem-iOS/Global/UIComponents/SwiftUI/CoachingContentView.swift
  Smeem-iOS/Smeem-iOS/Global/UIComponents/SwiftUI/CustomSegmentedControl.swift
  Smeem-iOS/Smeem-iOS/Global/UIComponents/SwiftUI/RandomTopicViewSwiftUI.swift
  Smeem-iOS/Smeem-iOS/Global/UIComponents/SwiftUI/SwiftUINavigationView.swift
  Smeem-iOS/Smeem-iOS/Presentation/Coaching/Components/CoachingCompleteView.swift
  Smeem-iOS/Smeem-iOS/Presentation/Coaching/Store/CoachingStore.swift
  Smeem-iOS/Smeem-iOS/Presentation/DetailDiary/DetailDiaryCoachedView.swift
Labels: Chore, Fix

#243 [TEST] 일기 코칭 및 상세 코칭 기능 테스트 플라이트 등록
  .github/workflows/smeemDev.yml
  Smeem-iOS/Smeem-iOS.xcodeproj/project.pbxproj
  Smeem-iOS/Smeem-iOS/Global/Constants/AmplitudeConstant.swift
  Smeem-iOS/Smeem-iOS/Global/Extensions/Double+.swift
  Smeem-iOS/Smeem-iOS/Global/Extensions/SwiftUI/HighlightModifier.swift
  Smeem-iOS/Smeem-iOS/Global/Extensions/SwiftUI/View+.swift
  Smeem-iOS/Smeem-iOS/Global/Extensions/UIViewController+.swift
  Smeem-iOS/Smeem-iOS/Global/UIComponents/SmeemComponent/LoadingView/SmemeLoadingView.swift
  Smeem-iOS/Smeem-iOS/Global/UIComponents/SmeemComponent/Toast/SmemeToastView.swift
  Smeem-iOS/Smeem-iOS/Global/UIComponents/SwiftUI/CoachingComparisonView.swift
  Smeem-iOS/Smeem-iOS/Global/UIComponents/SwiftUI/CoachingContentView.swift
  Smeem-iOS/Smeem-iOS/Global/UIComponents/SwiftUI/CustomSegmentedControl.swift
  Smeem-iOS/Smeem-iOS/Global/UIComponents/SwiftUI/FloatingButtonsSwiftUIView.swift
  Smeem-iOS/Smeem-iOS/Global/UIComponents/SwiftUI/RandomTopicViewSwiftUI.swift
  Smeem-iOS/Smeem-iOS/Global/UIComponents/SwiftUI/ScrollableDiaryView.swift
  Smeem-iOS/Smeem-iOS/Global/UIComponents/SwiftUI/SwiftUINavigationView.swift
  Smeem-iOS/Smeem-iOS/Global/UIComponents/UIViewConponent/CoachingComparisonView.swift
  Smeem-iOS/Smeem-iOS/Global/UIComponents/UIViewConponent/CoachingCompletedView.swift
  Smeem-iOS/Smeem-iOS/Global/UIComponents/UIViewConponent/CoachingExplanationView.swift
  Smeem-iOS/Smeem-iOS/Global/UIComponents/UIViewConponent/CustomSegmentedControl.swift
  Smeem-iOS/Smeem-iOS/Global/UIComponents/UIViewConponent/SwiftUINavigationView.swift
  Smeem-iOS/Smeem-iOS/Network/API/DetailDiary/DetailDiaryEndPoint.swift
  Smeem-iOS/Smeem-iOS/Network/NetworkDataModel/DetailDiary/DetailDiaryResponse.swift
  Smeem-iOS/Smeem-iOS/Presentation/Coaching/CoachingCompleteView.swift
  Smeem-iOS/Smeem-iOS/Presentation/Coaching/Components/CoachingCompleteView.swift
  Smeem-iOS/Smeem-iOS/Presentation/Coaching/Components/DiaryDetailView.swift
  Smeem-iOS/Smeem-iOS/Presentation/Coaching/Store/CoachingStore.swift
  Smeem-iOS/Smeem-iOS/Presentation/Coaching/View/CoachingView.swift
  Smeem-iOS/Smeem-iOS/Presentation/DetailDiary/DetailDiaryCoachedView.swift
  Smeem-iOS/Smeem-iOS/Presentation/DetailDiary/DetailDiaryViewController.swift
  Smeem-iOS/Smeem-iOS/Presentation/Diaries/View/Controllers/EditDiaryViewController.swift
  Smeem-iOS/Smeem-iOS/Presentation/DiaryComplete/CoachingStore.swift
  Smeem-iOS/Smeem-iOS/Presentation/DiaryComplete/CoachingView.swift
  Smeem-iOS/Smeem-iOS/Presentation/Home/HomeViewController.swift
  Smeem-iOS/Smeem-iOS/Presentation/Splash/Splah/ViewModel/SplashViewModel.swift
  Smeem-iOS/Smeem-iOSTests/Coaching/Service/CoachingServiceTest.swift
  Smeem-iOS/Smeem-iOSTests/Coaching/Store/CoachingStoreTest.swift
  Smeem-iOS/Smeem-iOSTests/Onboarding/ViewModel/SplashViewModelTest.swift
Labels: 짠 ✨, Feat, Setting

#244 [QA] 4차 QA 이슈 대응
  Smeem-iOS/Smeem-iOS/Global/UIComponents/SwiftUI/CustomSegmentedControl.swift
  Smeem-iOS/Smeem-iOS/Presentation/DetailDiary/DetailDiaryCoachedView.swift
Labels: 짠 ✨, 쭌 🍆

#246 [Hotfix] #245 - 앱 백그라운드 진입시 발생하는 이슈 해결 및 기능 추가
  .github/workflows/smeem-release.yml
  Smeem-iOS/Smeem-iOS.xcodeproj/project.pbxproj
  Smeem-iOS/Smeem-iOS/Global/Constants/AmplitudeConstant.swift
  Smeem-iOS/Smeem-iOS/Global/UIComponents/SmeemComponent/Global/SmeemToastView.swift
  Smeem-iOS/Smeem-iOS/Global/UIComponents/SmeemComponent/NavigationBar/SmeemNavigationFactory.swift
  Smeem-iOS/Smeem-iOS/Network/Base/NetworkManager.swift
  Smeem-iOS/Smeem-iOS/Presentation/Coaching/Store/CoachingStore.swift
  Smeem-iOS/Smeem-iOS/Presentation/Coaching/View/CoachingView.swift
  Smeem-iOS/Smeem-iOS/Presentation/Correction/CorrectionViewController.swift
  Smeem-iOS/Smeem-iOS/Presentation/DetailDiary/DetailDiaryCoachedView.swift
  Smeem-iOS/Smeem-iOS/Presentation/DetailDiary/DetailDiaryViewController.swift
  Smeem-iOS/Smeem-iOS/Presentation/Diaries/View/Controllers/EditDiaryViewController.swift
  Smeem-iOS/Smeem-iOS/Presentation/EditUser/BadgeList/VC/BadgeListViewController.swift
  Smeem-iOS/Smeem-iOS/Presentation/EditUser/BadgeList/View/BadgeHeaderView.swift
  Smeem-iOS/Smeem-iOS/Presentation/EditUser/BadgeList/View/BadgeListTableViewCell.swift
  Smeem-iOS/Smeem-iOS/Presentation/EditUser/BadgeList/View/DetailBadgeCollectionViewCell.swift
  Smeem-iOS/Smeem-iOS/Presentation/MySummary/ViewModel/MySummaryViewModel2.swift
  Smeem-iOS/Smeem-iOS/Presentation/Splash/Splah/ViewModel/SplashViewModel.swift
  Smeem-iOS/Smeem-iOS/Supports/SceneDelegate.swift
  Smeem-iOS/Smeem-iOSTests/Onboarding/ViewModel/SplashViewModelTest.swift
Labels: 짠 ✨, Feat, Fix

#247 [RELEASE] 3.1.0 version 배포
  Smeem-iOS/Smeem-iOS.xcodeproj/project.pbxproj
  Smeem-iOS/Smeem-iOS/Global/UIComponents/SmeemComponent/Global/SmeemToastView.swift
  Smeem-iOS/Smeem-iOS/Global/UIComponents/SmeemComponent/NavigationBar/SmeemNavigationFactory.swift
  Smeem-iOS/Smeem-iOS/Network/Base/NetworkManager.swift
  Smeem-iOS/Smeem-iOS/Presentation/Correction/CorrectionViewController.swift
  Smeem-iOS/Smeem-iOS/Presentation/DetailDiary/DetailDiaryCoachedView.swift
  Smeem-iOS/Smeem-iOS/Presentation/EditUser/BadgeList/VC/BadgeListViewController.swift
  Smeem-iOS/Smeem-iOS/Presentation/EditUser/BadgeList/View/BadgeHeaderView.swift
  Smeem-iOS/Smeem-iOS/Presentation/EditUser/BadgeList/View/BadgeListTableViewCell.swift
  Smeem-iOS/Smeem-iOS/Presentation/EditUser/BadgeList/View/DetailBadgeCollectionViewCell.swift
  Smeem-iOS/Smeem-iOS/Presentation/MySummary/ViewModel/MySummaryViewModel2.swift
  Smeem-iOS/Smeem-iOS/Presentation/Splash/Splah/ViewModel/SplashViewModel.swift
  Smeem-iOS/Smeem-iOS/Supports/SceneDelegate.swift
  Smeem-iOS/Smeem-iOSTests/Onboarding/ViewModel/SplashViewModelTest.swift
Labels: 짠 ✨, Feat
